name: "CI"
on: [push,pull_request]

jobs:
  test:
    name: "Test images"
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
        go-version: ["1.19.x", "1.23.x"]
        target:
          - os: linux
          - os: windows
            ext: .exe
          - os: android
            args: -app-id calc.sha
          - os: web
          - os: freebsd
            arch: -amd64
# Calculator build is failing on CI
#          - os: freebsd
#            arch: -arm64
        exclude:
# See https://github.com/actions/runner/issues/1512 for this weird syntax
          - {runner: ubuntu-24.04-arm,
             target: {os: android, args: -app-id calc.sha}}
# Freebsd build on arm runner do not work at this time
          - {runner: ubuntu-24.04-arm,
             target: {os: freebsd, arch: -amd64}}

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: fyne-cross-images

      - name: Checkout fyne-cross repository
        uses: actions/checkout@v3
        with:
          repository: fyne-io/fyne-cross
          path: fyne-cross

      - name: Checkout calcultator repository
        uses: actions/checkout@v3
        with:
          repository: fyne-io/calculator
          path: calculator

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/fyne-cross
          key: ${{ runner.os }}-build-cache-${{ hashFiles('**/go.sum') }}
      
      - name: Install latest fyne-cross
        working-directory: fyne-cross
        run: go install

      - name: Build image
        working-directory: fyne-cross-images
        run: |
          make ${{ matrix.target.os }}${{ matrix.target.arch }}

      - name: Verify new image with calculator
        working-directory: calculator
        run: |
          fyne-cross \
            ${{ matrix.target.os }} \
            ${{ matrix.target.args }} \
            -debug -no-cache \
            -image docker.io/fyneio/fyne-cross-images:`cd ../fyne-cross-images && make version`-${{ matrix.target.os }}${{ matrix.target.arch }} \
            -name calculator${{ matrix.target.ext }}
      
